In [1]:
import numpy as np

In [2]:
A = np.array([[3, 2], [4, 1]])
print(A)

[[3 2]
 [4 1]]


In [3]:
autovalores, autovectores = np.linalg.eig(A)
print("Autovalores:", autovalores)
print("Autovectores:\n", autovectores)

Autovalores: [ 5. -1.]
Autovectores:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [4]:
A_calculada = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [5]:
print(A_calculada)

[[3. 2.]
 [4. 1.]]


In [6]:
A = np.array([[3,2], [2,3]])
print(A)

[[3 2]
 [2 3]]


In [7]:
print(A == A.T)  # Verificar

[[ True  True]
 [ True  True]]


In [8]:
autovalores, autovectores = np.linalg.eig(A)
print("Autovalores:", autovalores)
print("Autovectores:\n", autovectores)

Autovalores: [5. 1.]
Autovectores:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [9]:
# A = A_Transpuesta
# A = V * diag(λ) * V_inv donde:
# V = matriz de autovectores
# diag(λ) = matriz diagonal de autovalores
# V_inv = inversa de la matriz de autovectores
A_calculada = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
print(A_calculada)

[[3. 2.]
 [2. 3.]]
