In [ ]:
import numpy as np

In [39]:
A = np.array([[2,3], [5,7], [11,13]])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [40]:
U, D, V = np.linalg.svd(A)
print("U:\n", U)
print("D:\n", D)
print("V:\n", V)

U:
 [[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D:
 [19.40321383  0.71783924]
V:
 [[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [41]:
D_pseudo = np.zeros((A.shape[0], A.shape[1])).T
print("D_pseudo:\n", D_pseudo)

D_pseudo:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [42]:
print("Valores a reemplazar en D_pseudo:")
print(D_pseudo[:D.shape[0], :D.shape[0]])

Valores a reemplazar en D_pseudo:
[[0. 0.]
 [0. 0.]]


In [43]:
print("Valores a pondremos en D_pseudo:")
print(np.linalg.inv(np.diag(D)))

Valores a pondremos en D_pseudo:
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [44]:
print("D_pseudo:")
D_pseudo[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pseudo)

D_pseudo:
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


In [45]:
A_pseudo = V.T @ D_pseudo @ U.T
print("A_pseudo:\n", A_pseudo)

A_pseudo:
 [[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [46]:
A_pseudo_calc = np.linalg.pinv(A)
print("A_pseudo (np.linalg.pinv):\n", A_pseudo_calc)

A_pseudo (np.linalg.pinv):
 [[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [49]:
np.set_printoptions(suppress=True) # <- Esto es para no mostrar numeros tan pequeños y mostrarlos como 0
print(A_pseudo.dot(A))

[[ 1.  0.]
 [-0.  1.]]


In [51]:
np.set_printoptions(suppress=False) # <- Esto es para mostrar numeros tan pequeños y no mostrarlos como 0
print(A_pseudo.dot(A))

[[ 1.00000000e+00  1.55431223e-15]
 [-1.27675648e-15  1.00000000e+00]]


In [53]:
A_pseudo_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print(A_pseudo_2)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [54]:
print(A_pseudo)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
